/*
 * NVIC_config.h
 *
 *  Created on: Aug 17, 2022
 *      Author: FAROUK
 */

#ifndef MCAL_NVIC_NVIC_CONFIG_H_
#define MCAL_NVIC_NVIC_CONFIG_H_
/*
MNVIC_16_GROUP_0_SUB
MNVIC_8_GROUP_2_SUB
MNVIC_4_GROUP_4_SUB
MNVIC_2_GROUP_8_SUB
MNVIC_0_GROUP_16_SUB
*/
#define MNVIC_GRP_SUB		MNVIC_4_GROUP_4_SUB

#endif /* MCAL_NVIC_NVIC_CONFIG_H_ */
